RU = {
    "app_title": "WhoopHub — только мониторинг",
    "tab_dashboard": "Дашборд",
    "tab_system": "Система",
    "tab_3d": "3D Модель",
    "tab_rc": "RC Каналы",
    "tab_motors": "Моторы",
    "tab_attitude": "Горизонт",
    "tab_gps": "GPS Карта",
    "tab_video": "Видео",
    "tab_logs": "Логи",
    "tab_stats": "Статистика",
    "tab_history": "История",
    "tab_profiles": "Профили",
    "connect": "Подключить",
    "disconnect": "Отключить",
    "refresh": "Обновить",
    "port": "Порт:",
    "connected": "● Подключено",
    "disconnected": "● Отключено",
    "status_notice": "Только мониторинг — FC не изменяется",
    "drone_label": "Дрон:",
    "theme_btn_dark": "🌙 Тёмная",
    "theme_btn_light": "☀️ Светлая",
    "lang_btn": "EN",
}

EN = {
    "app_title": "WhoopHub — monitor only",
    "tab_dashboard": "Dashboard",
    "tab_system": "System",
    "tab_3d": "3D Model",
    "tab_rc": "RC Channels",
    "tab_motors": "Motors",
    "tab_attitude": "Horizon",
    "tab_gps": "GPS Map",
    "tab_video": "Video",
    "tab_logs": "Logs",
    "tab_stats": "Statistics",
    "tab_history": "History",
    "tab_profiles": "Profiles",
    "connect": "Connect",
    "disconnect": "Disconnect",
    "refresh": "Refresh",
    "port": "Port:",
    "connected": "● Connected",
    "disconnected": "● Disconnected",
    "status_notice": "Monitor only — FC is not modified",
    "drone_label": "Drone:",
    "theme_btn_dark": "🌙 Dark",
    "theme_btn_light": "☀️ Light",
    "lang_btn": "RU",
}


def get_lang(ru=True):
    return RU if ru else EN